import { Platform, StyleSheet } from 'react-native';
import { AppTheme } from '../../theme/desingSystem';

export const createCameraScannerStyles = (theme: AppTheme) =>
	StyleSheet.create({
		container: {
			flex: 1,
			justifyContent: 'center',
			backgroundColor: theme.colors.background,
		},
		camera: {
			flex: 1,
		},
		permissionContainer: {
			flex: 1,
			alignItems: 'center',
			justifyContent: 'center',
			padding: theme.spacing.xl,
			backgroundColor: theme.colors.background,
		},
		permissionText: {
			textAlign: 'center',
			marginBottom: theme.spacing.lg,
			fontSize: theme.typography.size.lg,
			fontFamily: theme.typography.fontFamily.default,
			color: theme.colors.foreground,
		},
		permissionErrorText: {
			color: theme.colors.destructive,
			marginBottom: theme.spacing.md,
		},
		overlay: {
			flex: 1,
			backgroundColor: 'rgba(0,0,0,0.4)',
			justifyContent: 'center',
			alignItems: 'center',
		},
		scanFrame: {
			width: 250,
			height: 250,
			borderWidth: 2,
			borderColor: theme.colors.primary,
			backgroundColor: 'transparent',
			borderRadius: theme.spacing.lg,
		},
		controls: {
			position: 'absolute',
			bottom: theme.spacing.huge * 2,
			left: 0,
			right: 0,
			flexDirection: 'row',
			justifyContent: 'center',
			alignItems: 'center',
		},
		captureButton: {
			width: 70,
			height: 70,
			borderRadius: 35,
			backgroundColor: 'rgba(255,255,255,0.3)',
			justifyContent: 'center',
			alignItems: 'center',
			marginHorizontal: theme.spacing.xl,
		},
		captureInner: {
			width: 50,
			height: 50,
			borderRadius: 25,
			backgroundColor: 'white',
		},
		titleContainer: {
			position: 'absolute',
			top: Platform.OS === 'ios' ? 60 : 40,
			left: 0,
			right: 0,
			alignItems: 'center',
		},
		closeButton: {
			position: 'absolute',
			top: Platform.OS === 'ios' ? 52 : 32,
			left: theme.spacing.lg,
			width: 40,
			height: 40,
			borderRadius: 20,
			backgroundColor: 'rgba(0,0,0,0.55)',
			alignItems: 'center',
			justifyContent: 'center',
			borderWidth: 1,
			borderColor: 'rgba(255,255,255,0.35)',
			zIndex: 20,
		},
		flashButton: {
			position: 'absolute',
			top: Platform.OS === 'ios' ? 52 : 32,
			right: theme.spacing.lg,
			width: 40,
			height: 40,
			borderRadius: 20,
			backgroundColor: 'rgba(0,0,0,0.55)',
			alignItems: 'center',
			justifyContent: 'center',
			borderWidth: 1,
			borderColor: 'rgba(255,255,255,0.35)',
			zIndex: 20,
		},
		bottomRightButton: {
			position: 'absolute',
			right: theme.spacing.xxxl + theme.spacing.xxxl,
			bottom: theme.spacing.huge * 2 + 10,
			width: 44,
			height: 44,
			borderRadius: 22,
			backgroundColor: 'rgba(0,0,0,0.6)',
			alignItems: 'center',
			justifyContent: 'center',
			borderWidth: 1,
			borderColor: 'rgba(255,255,255,0.35)',
			zIndex: 20,
		},
		titleText: {
			color: 'white',
			fontSize: theme.typography.size.lg,
			fontWeight: theme.typography.weight.bold,
			fontFamily: theme.typography.fontFamily.bold,
			textShadowColor: 'rgba(0,0,0,0.5)',
			textShadowOffset: { width: 0, height: 1 },
			textShadowRadius: 3,
		},
	});
