import { StyleSheet } from "react-native";
import { AppTheme } from "../../theme/desingSystem";

export const createHomeStyles = (theme: AppTheme) =>
    StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: theme.colors.background,
        },
        scrollContent: {
            paddingBottom: 100,
        },
        header: {
            paddingHorizontal: theme.spacing.xl,
            paddingBottom: theme.spacing.md,
        },
        headerTopRow: {
            flexDirection: 'row',
            alignItems: 'flex-start',
            justifyContent: 'space-between',
            gap: theme.spacing.md,
        },
        headerTextBlock: {
            flex: 1,
            paddingRight: theme.spacing.sm,
        },
        greetingLine: {
            fontSize: theme.typography.size.xl + 3,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.bold,
            fontWeight: theme.typography.weight.bold,
        },
        headerMessage: {
            marginTop: theme.spacing.xs,
            fontSize: theme.typography.size.base,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
            lineHeight: 22,
        },
        headerLogo: {
            width: 30,
            height: 30,
            marginTop: 2,
        },
        userName: {
            fontSize: theme.typography.size.xxl,
            fontWeight: theme.typography.weight.bold,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.bold,
            marginTop: theme.spacing.xs,
        },
        searchContainer: {
            paddingHorizontal: theme.spacing.xl,
            marginTop: theme.spacing.md,
        },
        searchInputWrapper: {
            flexDirection: "row",
            alignItems: "center",
            backgroundColor: theme.colors.card,
            borderRadius: theme.radius.xl,
            paddingHorizontal: theme.spacing.lg,
            paddingVertical: theme.spacing.md,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        searchIcon: {
            marginRight: theme.spacing.md,
        },
        searchInput: {
            flex: 1,
            fontSize: theme.typography.size.base,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.default,
        },
        section: {
            marginTop: theme.spacing.xxl,
            paddingHorizontal: theme.spacing.xl,
        },
        sectionHeader: {
            flexDirection: "row",
            alignItems: "flex-start",
            marginBottom: theme.spacing.lg,
        },
        monthHeaderContent: {
            flex: 1,
            alignItems: 'center',
            paddingHorizontal: theme.spacing.sm,
        },
        monthNavButton: {
            width: 34,
            height: 34,
            borderRadius: theme.radius.full,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: theme.colors.card,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        sectionTitle: {
            fontSize: theme.typography.size.xl,
            fontWeight: theme.typography.weight.bold,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.bold,
        },
        monthLabel: {
            fontSize: theme.typography.size.xl + 2,
            fontWeight: theme.typography.weight.bold,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.bold,
            textTransform: 'uppercase',
            letterSpacing: 0.6,
            textAlign: 'center',
        },
        sectionSubtitle: {
            fontSize: theme.typography.size.sm,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
            marginTop: theme.spacing.xs,
        },
        weatherBanner: {
            marginHorizontal: theme.spacing.xl,
            marginTop: theme.spacing.xs,
            marginBottom: theme.spacing.sm,
            flexDirection: 'row',
            alignItems: 'center',
            gap: theme.spacing.md,
            paddingHorizontal: theme.spacing.md,
            paddingVertical: theme.spacing.sm,
            borderRadius: theme.radius.xl,
            borderWidth: 1,
            shadowColor: '#000000',
            shadowOpacity: 0.04,
            shadowRadius: 10,
            shadowOffset: {
                width: 0,
                height: 4,
            },
            elevation: 1,
        },
        weatherIconWrap: {
            width: 34,
            height: 34,
            borderRadius: theme.radius.full,
            alignItems: 'center',
            justifyContent: 'center',
        },
        weatherMessage: {
            flex: 1,
            fontSize: theme.typography.size.sm,
            lineHeight: 19,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.semibold,
        },
        loadingCard: {
            minHeight: 220,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: theme.colors.card,
            borderRadius: theme.radius.xl,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        summaryNotice: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: theme.spacing.sm,
            marginBottom: theme.spacing.md,
            paddingHorizontal: theme.spacing.md,
            paddingVertical: theme.spacing.sm,
            borderRadius: theme.radius.lg,
            backgroundColor: theme.colors.destructive + '14',
            borderWidth: 1,
            borderColor: theme.colors.destructive + '2A',
        },
        summaryNoticeText: {
            flex: 1,
            fontSize: theme.typography.size.sm,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.default,
            lineHeight: 18,
        },
        calendarCard: {
            backgroundColor: theme.colors.card,
            borderRadius: theme.radius.xl,
            padding: theme.spacing.lg,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        weekRow: {
            flexDirection: 'row',
            marginBottom: theme.spacing.sm,
        },
        weekDayLabel: {
            flex: 1,
            textAlign: 'center',
            fontSize: theme.typography.size.sm,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.semibold,
            textTransform: 'uppercase',
            letterSpacing: 0.6,
        },
        calendarGrid: {
            flexDirection: 'row',
            flexWrap: 'wrap',
        },
        calendarCellBlank: {
            width: '14.2857%',
            aspectRatio: 0.92,
        },
        calendarCell: {
            width: '14.2857%',
            aspectRatio: 0.92,
            borderRadius: theme.radius.lg,
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: theme.spacing.xs,
        },
        /* keep cell background neutral; selected indicator is a circular number */
        calendarCellSelected: {},
        calendarDayCircle: {
            width: 36,
            height: 36,
            borderRadius: 36,
            alignItems: 'center',
            justifyContent: 'center',
        },
        calendarDayCircleSelected: {
            width: 36,
            height: 36,
            borderRadius: 36,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: theme.colors.tertiary,
        },
        calendarCellToday: {
            borderWidth: 1,
            borderColor: theme.colors.primary,
        },
        calendarDayNumber: {
            fontSize: theme.typography.size.base,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.semibold,
        },
        calendarDayNumberSelected: {
            color: theme.colors.primaryForeground,
            fontWeight: theme.typography.weight.bold,
        },
        calendarDot: {
            marginTop: theme.spacing.xs,
            width: 7,
            height: 7,
            borderRadius: 7,
            backgroundColor: theme.colors.primary,
        },
        calendarDotWrap: {
            marginTop: theme.spacing.xs,
            width: 14,
            height: 14,
            alignItems: 'center',
            justifyContent: 'center',
        },
        calendarDotEmoji: {
            fontSize: 12,
            lineHeight: 14,
            textAlign: 'center',
        },
        calendarDotPlaceholder: {
            marginTop: theme.spacing.xs,
            width: 14,
            height: 14,
        },
        listStack: {
            gap: theme.spacing.md,
        },
        reminderCard: {
            flexDirection: 'row',
            alignItems: 'flex-start',
            gap: theme.spacing.md,
            backgroundColor: theme.colors.card,
            borderRadius: theme.radius.xl,
            padding: theme.spacing.lg,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        pendingCard: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: theme.spacing.md,
            backgroundColor: theme.colors.card,
            borderRadius: theme.radius.xl,
            padding: theme.spacing.lg,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        pendingContent: {
            flex: 1,
        },
        pendingHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: theme.spacing.md,
        },
        reminderIconWrap: {
            width: 42,
            height: 42,
            borderRadius: theme.radius.full,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: theme.colors.accent,
        },
        reminderContent: {
            flex: 1,
        },
        reminderTitle: {
            fontSize: theme.typography.size.base,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.semibold,
        },
        reminderMetaRow: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            alignItems: 'center',
            gap: theme.spacing.sm,
            marginTop: 2,
        },
        reminderSubtitle: {
            fontSize: theme.typography.size.sm,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
        },
        reminderWaterRow: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 4,
        },
        reminderWaterText: {
            fontSize: theme.typography.size.sm,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.semibold,
        },
        reminderMeta: {
            marginTop: theme.spacing.xs,
            fontSize: theme.typography.size.sm,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.default,
        },
        overdueChip: {
            paddingHorizontal: theme.spacing.sm,
            paddingVertical: theme.spacing.xs,
            borderRadius: theme.radius.full,
            backgroundColor: theme.colors.destructive,
            color: theme.colors.destructiveForeground,
            fontSize: theme.typography.size.sm,
            fontFamily: theme.typography.fontFamily.semibold,
            overflow: 'hidden',
        },
        statsContainer: {
            flexDirection: "row",
            gap: theme.spacing.md,
            marginTop: theme.spacing.lg,
        },
        statCard: {
            flex: 1,
            backgroundColor: theme.colors.card,
            borderRadius: theme.radius.xl,
            padding: theme.spacing.lg,
            alignItems: "center",
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        statNumber: {
            fontSize: theme.typography.size.xxl,
            fontWeight: theme.typography.weight.bold,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.bold,
        },
        statLabel: {
            fontSize: theme.typography.size.sm,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
            marginTop: theme.spacing.xs,
            textAlign: "center",
        },
        plantCard: {
            backgroundColor: theme.colors.card,
            borderRadius: theme.radius.xl,
            padding: theme.spacing.lg,
            marginBottom: theme.spacing.md,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        plantCardHeader: {
            flexDirection: "row",
            alignItems: "center",
        },
        plantImage: {
            width: 60,
            height: 60,
            borderRadius: theme.radius.lg,
            backgroundColor: theme.colors.muted,
        },
        plantImagePlaceholder: {
            width: 60,
            height: 60,
            borderRadius: theme.radius.lg,
            backgroundColor: theme.colors.accent,
            justifyContent: "center",
            alignItems: "center",
        },
        plantInfo: {
            flex: 1,
            marginLeft: theme.spacing.md,
        },
        plantName: {
            fontSize: theme.typography.size.lg,
            fontWeight: theme.typography.weight.bold,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.bold,
        },
        plantCategory: {
            fontSize: theme.typography.size.sm,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
            marginTop: 2,
        },
        statusBadge: {
            flexDirection: "row",
            alignItems: "center",
            paddingHorizontal: theme.spacing.md,
            paddingVertical: theme.spacing.xs,
            borderRadius: theme.radius.full,
            alignSelf: "flex-start",
            marginTop: theme.spacing.sm,
        },
        statusText: {
            fontSize: theme.typography.size.sm,
            fontWeight: theme.typography.weight.semibold,
            fontFamily: theme.typography.fontFamily.semibold,
            marginLeft: theme.spacing.xs,
        },
        pestsSection: {
            marginTop: theme.spacing.md,
            paddingTop: theme.spacing.md,
            borderTopWidth: 1,
            borderTopColor: theme.colors.border,
        },
        pestsTitle: {
            fontSize: theme.typography.size.sm,
            fontWeight: theme.typography.weight.semibold,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.semibold,
            marginBottom: theme.spacing.sm,
        },
        pestTag: {
            flexDirection: "row",
            alignItems: "center",
            paddingHorizontal: theme.spacing.md,
            paddingVertical: theme.spacing.xs,
            borderRadius: theme.radius.lg,
            marginRight: theme.spacing.sm,
            marginBottom: theme.spacing.sm,
        },
        pestName: {
            fontSize: theme.typography.size.sm,
            fontWeight: theme.typography.weight.semibold,
            fontFamily: theme.typography.fontFamily.semibold,
            marginLeft: theme.spacing.xs,
        },
        pestsRow: {
            flexDirection: "row",
            flexWrap: "wrap",
        },
        emptyState: {
            backgroundColor: theme.colors.card,
            borderRadius: theme.radius.xl,
            padding: theme.spacing.xxl,
            alignItems: "center",
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        emptyStateText: {
            fontSize: theme.typography.size.base,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
            textAlign: "center",
            marginTop: theme.spacing.md,
        },
        searchResultsContainer: {
            marginTop: theme.spacing.lg,
        },
        searchResultTitle: {
            fontSize: theme.typography.size.base,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
            marginBottom: theme.spacing.md,
        },
        waterCheckButton: {
            width: 40,
            height: 40,
            borderRadius: theme.radius.full,
            borderWidth: 1.5,
            borderColor: theme.colors.border,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: theme.colors.card,
            alignSelf: 'center',
        },
        waterCheckButtonActive: {
            backgroundColor: theme.colors.accent,
            borderColor: theme.colors.primary,
        },
    });
