import { StyleSheet } from "react-native";
import { AppTheme } from "../../theme/desingSystem";

export const createHomeStyles = (theme: AppTheme) =>
    StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: theme.colors.background,
        },
        scrollContent: {
            paddingBottom: 100,
        },
        header: {
            paddingHorizontal: theme.spacing.xl,
            paddingTop: theme.spacing.lg,
            paddingBottom: theme.spacing.md,
        },
        greeting: {
            fontSize: theme.typography.size.lg,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
        },
        userName: {
            fontSize: theme.typography.size.xxl,
            fontWeight: theme.typography.weight.bold,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.bold,
            marginTop: theme.spacing.xs,
        },
        searchContainer: {
            paddingHorizontal: theme.spacing.xl,
            marginTop: theme.spacing.md,
        },
        searchInputWrapper: {
            flexDirection: "row",
            alignItems: "center",
            backgroundColor: theme.colors.card,
            borderRadius: theme.radius.xl,
            paddingHorizontal: theme.spacing.lg,
            paddingVertical: theme.spacing.md,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        searchIcon: {
            marginRight: theme.spacing.md,
        },
        searchInput: {
            flex: 1,
            fontSize: theme.typography.size.base,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.default,
        },
        section: {
            marginTop: theme.spacing.xxl,
            paddingHorizontal: theme.spacing.xl,
        },
        sectionHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: theme.spacing.lg,
        },
        sectionTitle: {
            fontSize: theme.typography.size.xl,
            fontWeight: theme.typography.weight.bold,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.bold,
        },
        sectionSubtitle: {
            fontSize: theme.typography.size.sm,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
            marginTop: theme.spacing.xs,
        },
        statsContainer: {
            flexDirection: "row",
            gap: theme.spacing.md,
            marginTop: theme.spacing.lg,
        },
        statCard: {
            flex: 1,
            backgroundColor: theme.colors.card,
            borderRadius: theme.radius.xl,
            padding: theme.spacing.lg,
            alignItems: "center",
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        statNumber: {
            fontSize: theme.typography.size.xxl,
            fontWeight: theme.typography.weight.bold,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.bold,
        },
        statLabel: {
            fontSize: theme.typography.size.sm,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
            marginTop: theme.spacing.xs,
            textAlign: "center",
        },
        plantCard: {
            backgroundColor: theme.colors.card,
            borderRadius: theme.radius.xl,
            padding: theme.spacing.lg,
            marginBottom: theme.spacing.md,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        plantCardHeader: {
            flexDirection: "row",
            alignItems: "center",
        },
        plantImage: {
            width: 60,
            height: 60,
            borderRadius: theme.radius.lg,
            backgroundColor: theme.colors.muted,
        },
        plantImagePlaceholder: {
            width: 60,
            height: 60,
            borderRadius: theme.radius.lg,
            backgroundColor: theme.colors.accent,
            justifyContent: "center",
            alignItems: "center",
        },
        plantInfo: {
            flex: 1,
            marginLeft: theme.spacing.md,
        },
        plantName: {
            fontSize: theme.typography.size.lg,
            fontWeight: theme.typography.weight.bold,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.bold,
        },
        plantCategory: {
            fontSize: theme.typography.size.sm,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
            marginTop: 2,
        },
        statusBadge: {
            flexDirection: "row",
            alignItems: "center",
            paddingHorizontal: theme.spacing.md,
            paddingVertical: theme.spacing.xs,
            borderRadius: theme.radius.full,
            alignSelf: "flex-start",
            marginTop: theme.spacing.sm,
        },
        statusText: {
            fontSize: theme.typography.size.sm,
            fontWeight: theme.typography.weight.semibold,
            fontFamily: theme.typography.fontFamily.semibold,
            marginLeft: theme.spacing.xs,
        },
        pestsSection: {
            marginTop: theme.spacing.md,
            paddingTop: theme.spacing.md,
            borderTopWidth: 1,
            borderTopColor: theme.colors.border,
        },
        pestsTitle: {
            fontSize: theme.typography.size.sm,
            fontWeight: theme.typography.weight.semibold,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.semibold,
            marginBottom: theme.spacing.sm,
        },
        pestTag: {
            flexDirection: "row",
            alignItems: "center",
            paddingHorizontal: theme.spacing.md,
            paddingVertical: theme.spacing.xs,
            borderRadius: theme.radius.lg,
            marginRight: theme.spacing.sm,
            marginBottom: theme.spacing.sm,
        },
        pestName: {
            fontSize: theme.typography.size.sm,
            fontWeight: theme.typography.weight.semibold,
            fontFamily: theme.typography.fontFamily.semibold,
            marginLeft: theme.spacing.xs,
        },
        pestsRow: {
            flexDirection: "row",
            flexWrap: "wrap",
        },
        emptyState: {
            backgroundColor: theme.colors.card,
            borderRadius: theme.radius.xl,
            padding: theme.spacing.xxl,
            alignItems: "center",
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        emptyStateText: {
            fontSize: theme.typography.size.base,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
            textAlign: "center",
            marginTop: theme.spacing.md,
        },
        searchResultsContainer: {
            marginTop: theme.spacing.lg,
        },
        searchResultTitle: {
            fontSize: theme.typography.size.base,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
            marginBottom: theme.spacing.md,
        },
    });
