import { StyleSheet } from "react-native";
import { AppTheme } from "../../theme/desingSystem";

export const createPlantCareStyles = (theme: AppTheme) =>
    StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: theme.colors.background,
        },
        scrollContent: {
            paddingBottom: 100,
        },
        header: {
            paddingHorizontal: theme.spacing.xl,
            paddingTop: theme.spacing.lg,
            paddingBottom: theme.spacing.md,
        },
        headerTitle: {
            fontSize: theme.typography.size.xxl,
            fontWeight: theme.typography.weight.bold,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.bold,
        },
        headerSubtitle: {
            fontSize: theme.typography.size.base,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
            marginTop: theme.spacing.xs,
        },
        tabsContainer: {
            flexDirection: "row",
            paddingHorizontal: theme.spacing.xl,
            marginTop: theme.spacing.lg,
            gap: theme.spacing.md,
        },
        tab: {
            flex: 1,
            paddingVertical: theme.spacing.md,
            borderRadius: theme.radius.xl,
            alignItems: "center",
            backgroundColor: theme.colors.card,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        tabActive: {
            backgroundColor: theme.colors.primary,
            borderColor: theme.colors.primary,
        },
        tabText: {
            fontSize: theme.typography.size.base,
            fontWeight: theme.typography.weight.semibold,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.semibold,
        },
        tabTextActive: {
            color: theme.colors.primaryForeground,
        },
        tabCount: {
            fontSize: theme.typography.size.sm,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
            marginTop: 2,
        },
        tabCountActive: {
            color: theme.colors.primaryForeground,
            opacity: 0.8,
        },
        plantsContainer: {
            paddingHorizontal: theme.spacing.xl,
            marginTop: theme.spacing.xxl,
        },
        plantCard: {
            backgroundColor: theme.colors.card,
            borderRadius: theme.radius.xl,
            marginBottom: theme.spacing.lg,
            borderWidth: 1,
            borderColor: theme.colors.border,
            overflow: "hidden",
        },
        plantCardHeader: {
            flexDirection: "row",
            padding: theme.spacing.lg,
        },
        plantImage: {
            width: 80,
            height: 80,
            borderRadius: theme.radius.lg,
            backgroundColor: theme.colors.muted,
        },
        plantImagePlaceholder: {
            width: 80,
            height: 80,
            borderRadius: theme.radius.lg,
            backgroundColor: theme.colors.accent,
            justifyContent: "center",
            alignItems: "center",
        },
        plantMainInfo: {
            flex: 1,
            marginLeft: theme.spacing.lg,
        },
        plantNameRow: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
        },
        plantName: {
            fontSize: theme.typography.size.lg,
            fontWeight: theme.typography.weight.bold,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.bold,
            flex: 1,
        },
        favoriteIcon: {
            marginLeft: theme.spacing.sm,
        },
        plantCategory: {
            fontSize: theme.typography.size.sm,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
            marginTop: 2,
        },
        statusBadge: {
            flexDirection: "row",
            alignItems: "center",
            paddingHorizontal: theme.spacing.md,
            paddingVertical: theme.spacing.xs,
            borderRadius: theme.radius.full,
            alignSelf: "flex-start",
            marginTop: theme.spacing.sm,
        },
        statusText: {
            fontSize: theme.typography.size.sm,
            fontWeight: theme.typography.weight.semibold,
            fontFamily: theme.typography.fontFamily.semibold,
            marginLeft: theme.spacing.xs,
        },
        expandButton: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
            paddingVertical: theme.spacing.md,
            borderTopWidth: 1,
            borderTopColor: theme.colors.border,
            backgroundColor: theme.colors.muted,
        },
        expandButtonText: {
            fontSize: theme.typography.size.sm,
            color: theme.colors.primary,
            fontWeight: theme.typography.weight.semibold,
            fontFamily: theme.typography.fontFamily.semibold,
            marginRight: theme.spacing.xs,
        },
        plantDetails: {
            padding: theme.spacing.lg,
            borderTopWidth: 1,
            borderTopColor: theme.colors.border,
            backgroundColor: theme.colors.muted,
        },
        detailSection: {
            marginBottom: theme.spacing.lg,
        },
        detailSectionTitle: {
            fontSize: theme.typography.size.base,
            fontWeight: theme.typography.weight.bold,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.bold,
            marginBottom: theme.spacing.md,
        },
        detailGrid: {
            flexDirection: "row",
            flexWrap: "wrap",
            gap: theme.spacing.md,
        },
        detailItem: {
            width: "47%",
            backgroundColor: theme.colors.card,
            padding: theme.spacing.md,
            borderRadius: theme.radius.lg,
        },
        detailLabel: {
            fontSize: theme.typography.size.sm,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
        },
        detailValue: {
            fontSize: theme.typography.size.base,
            color: theme.colors.foreground,
            fontWeight: theme.typography.weight.semibold,
            fontFamily: theme.typography.fontFamily.semibold,
            marginTop: 2,
        },
        pestsContainer: {
            gap: theme.spacing.md,
        },
        pestCard: {
            backgroundColor: theme.colors.card,
            padding: theme.spacing.md,
            borderRadius: theme.radius.lg,
            borderLeftWidth: 4,
        },
        pestHeader: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
        },
        pestName: {
            fontSize: theme.typography.size.base,
            fontWeight: theme.typography.weight.bold,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.bold,
        },
        pestScientific: {
            fontSize: theme.typography.size.sm,
            color: theme.colors.mutedForeground,
            fontStyle: "italic",
            fontFamily: theme.typography.fontFamily.default,
            marginTop: 2,
        },
        dangerBadge: {
            paddingHorizontal: theme.spacing.md,
            paddingVertical: theme.spacing.xs,
            borderRadius: theme.radius.full,
        },
        dangerText: {
            fontSize: theme.typography.size.sm,
            fontWeight: theme.typography.weight.semibold,
            fontFamily: theme.typography.fontFamily.semibold,
        },
        pestDescription: {
            fontSize: theme.typography.size.sm,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
            marginTop: theme.spacing.sm,
            lineHeight: 20,
        },
        treatmentContainer: {
            marginTop: theme.spacing.md,
            padding: theme.spacing.md,
            backgroundColor: `${theme.colors.primary}15`,
            borderRadius: theme.radius.md,
        },
        treatmentLabel: {
            fontSize: theme.typography.size.sm,
            fontWeight: theme.typography.weight.semibold,
            color: theme.colors.primary,
            fontFamily: theme.typography.fontFamily.semibold,
        },
        treatmentText: {
            fontSize: theme.typography.size.sm,
            color: theme.colors.foreground,
            fontFamily: theme.typography.fontFamily.default,
            marginTop: theme.spacing.xs,
            lineHeight: 20,
        },
        noPests: {
            flexDirection: "row",
            alignItems: "center",
            backgroundColor: `${theme.colors.primary}15`,
            padding: theme.spacing.md,
            borderRadius: theme.radius.lg,
        },
        noPestsText: {
            fontSize: theme.typography.size.base,
            color: theme.colors.primary,
            fontFamily: theme.typography.fontFamily.default,
            marginLeft: theme.spacing.md,
        },
        careTypesContainer: {
            gap: theme.spacing.sm,
        },
        careTypeTag: {
            backgroundColor: theme.colors.card,
            paddingHorizontal: theme.spacing.md,
            paddingVertical: theme.spacing.sm,
            borderRadius: theme.radius.lg,
            marginRight: theme.spacing.sm,
            marginBottom: theme.spacing.sm,
        },
        careTypeName: {
            fontSize: theme.typography.size.sm,
            fontWeight: theme.typography.weight.semibold,
            color: theme.colors.primary,
            fontFamily: theme.typography.fontFamily.semibold,
        },
        careTypeDesc: {
            fontSize: theme.typography.size.sm,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
            marginTop: 2,
        },
        emptyState: {
            backgroundColor: theme.colors.card,
            borderRadius: theme.radius.xl,
            padding: theme.spacing.xxl,
            alignItems: "center",
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        emptyStateText: {
            fontSize: theme.typography.size.base,
            color: theme.colors.mutedForeground,
            fontFamily: theme.typography.fontFamily.default,
            textAlign: "center",
            marginTop: theme.spacing.md,
        },
        toxicWarning: {
            flexDirection: "row",
            alignItems: "center",
            backgroundColor: `${theme.colors.destructive}15`,
            padding: theme.spacing.md,
            borderRadius: theme.radius.lg,
            marginTop: theme.spacing.md,
        },
        toxicText: {
            fontSize: theme.typography.size.sm,
            color: theme.colors.destructive,
            fontFamily: theme.typography.fontFamily.default,
            marginLeft: theme.spacing.sm,
            flex: 1,
        },
    });
